# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Javascript Algorithm CI

on: [push, pull_request]

permissions: write-all

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2

    - name: npm install, build, and test
      run: |
        npm install doctest
        npm install standard --save-dev
        npx doctest **/*.js || true  # TODO: Add all doctests
        npx standard
        npm ci
        npm run build --if-present
        
      env:
        CI: true
        
    - name: Run the tests
      run: npm test -- --coverage
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
