# This GitHub Action updates the DIRECTORY.md file (if needed) when doing a git push
name: Update Directory

on:
  push:
    branches-ignore:
      "master"

jobs:
  updateDirectory:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: üì¶ Install dependencies
        run: npm ci

      - name: üóÑÔ∏è Create Directory from JS files
        run: node .github/workflows/UpdateDirectory.js

      - name: Configure Github Action
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: ü§ì Commit & push new Directory (if needed)
        run: |
          if [[ `git status --porcelain` ]]; then
            git commit -am "Updated Documentation in README.md"
            git push
          else
            echo "NO CHANGES DETECTED"
          fi
